### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by maxyboiii** [cgisca/PGSGP#1]
this guy and me have the same problem:
https://godotengine.org/qa/52856/android-plugin-using-play-services-nearby

**Comment by himaghnam** [comment]
I added these lines in gradle.properties in build folder and it is working for me now
``` 
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by BThacker** [comment]
I had a similar issue caused by duplicate code. Adding the:
android.useAndroidX=true
android.enableJetifier=true

to gradle.properties seems to have resolved it for me as well, will do further testing soon

**Comment by cgisca** [comment]
Closing this issue as it seems to be fixed by adding  to `gradle.properties`
`
android.useAndroidX=true
android.enableJetifier=true
`
