### ISSUE TITLE
Demo script has an error

### ISSUE THREAD

**Issue by cgeadas** [cgisca/PGSGP#11]
Demo script (Main.gd) has an error on line 10.
It is:
`		play_games_services.init(get_instance_id())`
(which gives a runtime error)

When it should be:
`		play_games_services.init(get_instance_id(), true)`

Or to be more in line with README.md:
```
  var show_popups := true # For example, your game can display a “Welcome back” or an “Achievements unlocked” pop-up. true for enabling it.
  play_games_services.init(get_instance_id(), show_popups)
```

**Comment by cgisca** [comment]
@cgeadas fixed it
