### ISSUE TITLE
Customize Google Drive Apps name

### ISSUE THREAD

**Issue by cgeadas** [cgisca/PGSGP#12]
Is it possible to customize the name that gets registered in Google Drive for the apps using this module?
I'm getting help-luigi-8677927, which is a mixture of my app's name and id. But I would like it to look like the other apps, who get proper names.

![GoogleDriveAppsScreenshot](https://user-images.githubusercontent.com/61761248/77375453-690ff780-6d65-11ea-980c-bc12570c4407.jpg)

This change is not only cosmetic since it raises the app credibility towards users.
Any change to allow for this kind of customization?

**Comment by cgisca** [comment]
@cgeadas I am not sure this can be done using Google Play games services. I am guessing that this configuration can be done on [Google API Console](https://console.developers.google.com/) , section `OAuth consent screen` . There you can Edit your app by adding app logo, name and others. But I am not 100 % sure.  Another way, a hack, is to edit app id when creating a new project on [Google API Console](https://console.developers.google.com/). 
If you found out how to configure it, please let me know here in this thread. Thank you.

**Comment by cgeadas** [comment]
@cgisca The OAuth screen doesn't seem to make any difference for this matter. Also, there's a Drive UI Integration page (console.developers.google.com/apis/api/drive.googleapis.com/drive_sdk) that seems to be made for a deeper kind of integration (like Google Docs). The folder name that is created in Google Drive is a sort fo concat between my games app name and app ID. I don't know how this is determined. From a quick google search, it may be during the creation of  the SCOPE_APPFOLDER scope (https://developers.google.com/games/services/android/savedgames), but since I don't know the programming language neither the API, I may be (probably am) wrong.
If I find anything useful, I'll report it. Thank you for your work, you have a great module here.

**Comment by cgisca** [comment]
@cgeadas I have checked it and for configuring the look of your app in google drive you need to do it on [Google API Console](https://console.developers.google.com/apis/api/drive.googleapis.com) of your project. 
To do this you need to have Google Drive APIs enabled, then access it and go to `Drive UI Integration` and there you can provide application name, icons, and others.

![Screenshot from 2020-04-12 23-21-40](https://user-images.githubusercontent.com/4255200/79078962-ab00dd80-7d14-11ea-95fc-02282787d121.png)

**Comment by cgeadas** [comment]
@cgisca  You're pointing me to the page I've mentioned in the last comment :-) That page is for applications that use/integrate with Google Drive visible space. Games that integrate with Google Drive use hidden app data, which is a different process. You can check that out with your own Google Drive account  - you can see that games' hidden folders don't have an icon, for example. It's a different thing. I've tried that :-)

**Comment by cgisca** [comment]
@cgeadas have you tried to access `Drive UI Integration` from Google Drive API, as I described earlier? And it still does not work for you? I mean you don't see the app name changed as you provided on `Drive UI Integration` page? 

I have tested this scenario, with one of my app, that has `Hidden app data` , and I was able to see the changes in Google drive -> Settings -> Manage Apps. 
Changes made on `Drive UI Integration` were propagated almost instantly in google drive - manage apps section .

**Comment by cgeadas** [comment]
@cgisca What value do you use for the required "Open URL " field? The icon, which is mandatory, I can make one, but I'm at a loss regarding this required field.

**Comment by cgeadas** [comment]
With my new game (Turzzle), the name display correctly and I made no change on `Drive UI Integration`.

<img width="500" alt="Screenshot 2020-06-09 at 00 39 32" src="https://user-images.githubusercontent.com/61761248/84090514-f4ef0280-a9e9-11ea-8581-5e181adfac33.png">

Something during the latest developments (of this plugin) must have fixed it.
Closing this issue.
