### ISSUE TITLE
Callbacks do not work

### ISSUE THREAD

**Issue by tksney** [cgisca/PGSGP#13]
I am getting an error in the Callbacks, in all of them. Everything works, but if I try to call a print () on some callback I get this error.

```
E godot   : **ERROR**: Condition "!obj" is true.
E godot   :  At: platform/android/java_godot_lib_jni.cpp:1383:Java_org_godotengine_godot_GodotLib_calldeferred() - Condition "!obj" is true.
```

The biggest problem is that I can't use the `func _on_game_load_success (saved_game):` since I only get errors.

Do you have any idea what it might be?

**Comment by cgisca** [comment]
@tksney sorry for the inconvinience. Could you please download latest version from this tag (1.2.0) https://github.com/cgisca/PGSGP/releases/tag/1.2.0 , and try again. It was an error that is fixed in this version. Thanks.

**Comment by tksney** [comment]
Ah, ok. I will update everything and try. Thank you for your time, and for your work.

**Comment by tksney** [comment]
Now it's working, thank you very much
