### ISSUE TITLE
Gradle build error when plug-in is included

### ISSUE THREAD

**Issue by tx350z** [cgisca/PGSGP#14]
Followed instructions for adding android-pgs-plugin to the project, rebuilt android custom build template, attempted to android export (tried debug and release) and received gradle build error.
I have no other plug-ins in the but tried removing the two lines from the plug-in AndroidManifest.xml. Received the same build error.

Sorry the gradle output window does not allow copying so I've included a image capture.

![GradleBuildError](https://user-images.githubusercontent.com/956567/78504498-4bfb0180-7733-11ea-8e85-f0b32d809973.png)

**Comment by cgisca** [comment]
@tx350z from the error you get, you need to add next lines
 `android.useAndroidX=true`
 `android.enableJetifier=true`
to the gradle.properties file, that you can find inside android folder of your project: `../android/build/gradle.properties`

**Comment by tx350z** [comment]
Thank you, that solved the build error. Could you add something to the README mentioning this? I'm not seeing much info about migrating to AndrdoidX.
