### ISSUE TITLE
ERROR: _export_project_to_path: Failed to export the project for platform 'Andro id'.    At: editor/project_export.cpp:977

### ISSUE THREAD

**Issue by titangamingglt** [cgisca/PGSGP#17]
how to fix this?

**Comment by titangamingglt** [comment]
![Untitled](https://user-images.githubusercontent.com/61984082/82252792-479a4900-996d-11ea-9c21-767a65648b2a.png)

**Comment by titangamingglt** [comment]
Solved this by adding two lines in gradle.properties file:

android.useAndroidX=true
android.enableJetifier=true

**Comment by cgisca** [comment]
Closing the issue as it was solved
