### ISSUE TITLE
Problems with sign in

### ISSUE THREAD

**Issue by GhosTheKaos3150** [cgisca/PGSGP#18]
I'm with problems at Sign In in my game. It always ends up failing with code 4. I tried other issues solutions, but even changing the SHA1 fingerprint is not solving the problem. 

**What I've already done:**
I'm initializing the plugin as it is shown in _How to use_. The Google Drive API is already installed. The SHA1 fingerprint is the same in the API, in the Play Console and Keystore. I'm also using my game Keystore for debugging since the debug.keystore has another fingerprint. Play Game Service and Play Game Management are installed too. The app_id at _ids.xml_ is the same as in the Play Console, and I'm already using the following lines at gradle.properties:

android.useAndroidX=true
android.enableJetifier=true

What is missing? I've tried everything I've found! D:

**Comment by tx350z** [comment]
I had the same problem. In my case, the cause was a missing permission for Google Drive - the save game functions need that permission. Go to Google API & Services console and add Google Drive permission.

**Comment by GhosTheKaos3150** [comment]
If giving Google Drive permission is add it to my app on API Console, I already did this. 

Google Drive API is set, and the SHA1 is the same as in Google Play Console in both game and API Console.

**Comment by tx350z** [comment]
What call is returning the error code? Status code 4 from GPGS translates to "SIGN_IN_REQUIRED". Here is the Doc: https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes

Error code 4 means you have not successfully connected your app to GPGS. There are many "0-day" conditions you need to handle (and test thoroughly). For example, Google Play Games app may not be installed on the user's device, the user may not have a Play Games login, your game must be authorized by the user to connect to Play Games, the user may not have "auto-login" set in Play Games, etc. Generally these conditions can be handled by repeatedly calling the singleton.sign_in() method until you get a successful sign in.

Also be aware the singleton always attempts to use the most recent Play Games credentials. This works for most users. However, if a user is on a shared device that has multiple Play Games profiles, it doesn't work correctly. And it is almost impossible to force the singleton to use a login other than the one most recently used.

Hope this helps.

**Comment by GhosTheKaos3150** [comment]
Actually, that helped a lot! The problem was two different accounts at my Play Games (I'm testing it before releasing). Thanks!
