### ISSUE TITLE
save_snapshot not working

### ISSUE THREAD

**Issue by cgeadas** [cgisca/PGSGP#20]
I'm using release 1.2.0. When I call save_snapshot I get two times the _on_game_saved_fail callback (yes, 2 times for each call). Show_saved_games, however, works -  I get a window showing no saves. Sign_in is successful, I get the _on_sign_in_success callback with the account_id and I also get the welcome notification window in the game.

I've checked the following points:
- I'm calling play_games_services.init with the enable_save_games = true
- I have the correct APIs connected to the game (as picture)

![image](https://user-images.githubusercontent.com/61761248/84182781-d852d900-aa82-11ea-9715-27c5bc6f798d.png)

- I have all the APKs authorised (the debug, production and the Google signed APK)
![image](https://user-images.githubusercontent.com/61761248/84183730-421fb280-aa84-11ea-8ce8-2c29e3a9e699.png)

- I have no errors on the API's console (as picture)
![image](https://user-images.githubusercontent.com/61761248/84183144-544d2100-aa83-11ea-8f6c-1882d474fb1d.png)

- I've made the code as simple as possible for testing purposes (as shown; nome_snap is "Snap1")
```
func save_game(nome_snap) -> void:
		
	if play_games_services:
		play_games_services.save_snapshot(nome_snap, "1", "Gamesave")
```

The call of save_game is very simple, just:
`GPlay.save_game("Snap1")`
(I'm using an autoload for the play_games_services but using a regular scene or just script gives the same result)

Every time I call the method, I get 2 times "Game saved fail", in the following callback:
```
func _on_game_saved_fail():
	print("Game saved fail")
```

The log doesn't provide any useful information:
```
adb logcat -s godot
--------- beginning of crash
--------- beginning of system
--------- beginning of main
06-09 19:25:15.868 25829 25886 I godot   : Loading Android module: org/godotengine/godot/GodotAdMob
06-09 19:25:15.876 25829 25886 I godot   : Loading Android module: org/godotengine/godot/PlayGameServices
06-09 19:25:16.005 25829 25886 I godot   : Godot Engine v3.2.1.stable.official - https://godotengine.org
06-09 19:25:16.018 25829 25886 I godot   : OpenGL ES 2.0 Renderer: Adreno (TM) 508
06-09 19:25:16.318 25829 25886 I godot   :  
06-09 19:25:17.401 25829 25886 D godot   : AdMob: init with content rating options
06-09 19:25:19.138 25829 25886 I godot   : Success
06-09 19:25:19.138 25829 25886 I godot   : 103236622368481239XXX
06-09 19:25:22.027 25829 25829 W godot   : AdMob: onAdLoaded
06-09 19:25:44.444 25829 25886 I godot   : Game saved fail
06-09 19:25:44.445 25829 25886 I godot   : Game saved fail
```
I'm out of ideas here. I think I'm not missing anything.
Is this a bug?

**Comment by tx350z** [comment]
In my attempt to integrate GPGS into my game I noticed that _ready() is sometimes called after returning from a GPGS pop-up. You might try calling the singleton.init() with the enable pop-ups parameter set to false.

**Comment by cgeadas** [comment]
@tx350z The result is the same - I mean, I don't get the welcome window, but the game still doesn't save and I still get the fail message twice.

**Comment by tx350z** [comment]
The one thing I see in the log is you appear to be calling GPGS then calling Admod before the GPGS call completes. You should wait for GPGS to complete all callbacks before calling Admob because it uses callbacks also.

You might want to remove Admob calls until you have GPGS working, then add Admob just to be sure they are not conflicting.

**Comment by cgeadas** [comment]
Admob was installed before, and was working correctly before installing GPGS (one change at a time is a good policy). Anyway, I've followed your suggestion and completely removed Admod, leaving just GPGS. The result was the same.
(In my previous game I have both working together, but the versions are not the same and I didn't tried the savegame feature.)

**Comment by cgeadas** [comment]
The problem was that Godot, when debugging to Android does not sign the apk with the debug keystore specified in the Export Preset but, instead, uses the debug keystore specified at Editor Settings so, the debug signatures were different, leading to GPGS not recognising the game (although sign-in worked well...) and game saves not working.

Yet, load and save continue call twice the callbacks.
