### ISSUE TITLE
Demo project doesn't compile

### ISSUE THREAD

**Issue by cgeadas** [cgisca/PGSGP#21]
When compiling the demo project, the process stops with error:
<img width="1552" alt="Screenshot 2020-06-15 at 21 20 39" src="https://user-images.githubusercontent.com/61761248/84702268-3e8d9f00-af4e-11ea-8712-e52cda52de9d.png">

This error is solved by adding the following lines to `gradle.properties` from the build (gradle) folder:
```
android.useAndroidX=true
android.enableJetifier=true
```

Since it's a requirement to work, this should be stated in the readme.md file.

**Comment by cgisca** [comment]
I have updated the plugin to use the new android plugin system for godot 3.2.2+ , and this could be outdated. Tell me if you encounter the same issue with the new plugin, and I will update Readme.md file. Thank you.

**Comment by cgisca** [comment]
Closing the issue.
