### ISSUE TITLE
Get more account data

### ISSUE THREAD

**Issue by PhilippGackstatter** [cgisca/PGSGP#34]
First of all, thanks for this plugin!

I read over the [official guide](https://developers.google.com/games/services/android/signin) and when signing in a user, one can get a `GoogleSignInAccount`. [It gives access](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInAccount) to various information such as name, email, account_id, ...

In the plugin, it seems, I can only get access to the `account_id` that is passed to the `_on_sign_in_success` callback. Is it possible to get access to the other information as well or would this require rewriting parts of the plugin?

Thanks!

**Comment by cgisca** [comment]
Hi @PhilippGackstatter ,
Unfortunately at the moment plugin does not support this functionality.I will add it for the next release. When it will be ready I will let you know in this thread.

Thank you

**Comment by tytkal** [comment]
Hi @cgisca 
Thanks for the amazing  plugin I already update the project to support more data, I want to push the changes into new branch but i don't have the permission to do it.
Thanks.

**Comment by cgisca** [comment]
Thank you @tytkal, 
please open a pull request and I will review it. thanks

**Comment by tytkal** [comment]
@cgisca  Done https://github.com/cgisca/PGSGP/pull/35

**Comment by cgisca** [comment]
@PhilippGackstatter please check the new release for the Profile info functionality. See [Player Info section](https://github.com/cgisca/PGSGP/tree/2.1.0#player-info) in Readme.md .You'll get info like name, title, display name, player id, image url, banner image url, level info. The only piece of info that is missing is email address, but I will add that when I will implement the next feature, which is [Friends beta](https://developers.google.com/games/services/common/concepts/friends).

**Comment by PhilippGackstatter** [comment]
That's perfect, thanks for adding this so quickly! Much appreciated :pray:
