### ISSUE TITLE
Google Drive API access

### ISSUE THREAD

**Issue by BilawalSarwar** [cgisca/PGSGP#37]
I have successfully implemented all services. The issue i am facing now is that users don't want to give access to google drive. In other words instead of explicitly asking for drive permission i want to authenticate with google sign.

**Comment by cgisca** [comment]
Hello @BilawalSarwar ,

there are 2 methods to initialize the plugin. 
1. var show_popups := true 
  play_games_services.init(show_popups)

2. play_games_services.initWithSavedGames(show_popups, "SavedGamesName")

If you use first method, it won't ask for Google Drive permission, but you won't be able to use saved game functionality. It will ask only if you are using 2nd method.

I am not sure I understood your statement. Are you telling that you want to use 2nd method to be able to use saved games functionality, and in the case for those users that are not allowing Google Drive permission, as a fallback it should init plugin without saved games functionality (like using method 1), so you could use other plugin's functionalities?
