### ISSUE TITLE
This is not an issue more of a doubt because, I am just starting out.

### ISSUE THREAD

**Issue by SoloCarryGuy** [cgisca/PGSGP#39]
Where is the Main.gd? Where you need to change to your app id? And, in this     
```
<meta-data android:name="com.google.android.gms.games.APP_ID"
   	    android:value="@string/app_id" />
```
Do I need to change the APP_ID here too?
Again, I am just staring out in programming so don't know much about it.

And, on the show leaderboard how to set it into a table, will playstore have a default table
Also, on unlocking achevement that icon on top of screen with exp earned will that also be done automatically?

**Comment by ulvido** [comment]
no need to change this text. just put it where it says

**Comment by SoloCarryGuy** [comment]
Thank you for the help @ulvido I got it running. Do I need to upload test track to google play every time, I need to test something like achievements or snapshots or can I just install it on my android using a usb and the google stuff will run?

**Comment by ulvido** [comment]
> Thank you for the help @ulvido I got it running. Do I need to upload test track to google play every time, I need to test something like achievements or snapshots or can I just install it on my android using a usb and the google stuff will run?

strangely me too. I needed to upload and download the produced apk every time. otherwise didn't work. app crashes.

**Comment by SoloCarryGuy** [comment]
@ulvido  And, its taking google so much time to publish apk right now. Due to the reduced staff issue they have. Thank you for the help though, I will ask for help if I get stuck again after I publish.

**Comment by ulvido** [comment]
you are welcome. you dont need to publish. just upload to the alpha channel and save. click review. and publish for alpha. download the alpha apk without waiting.

![image](https://user-images.githubusercontent.com/27722274/93049384-8fa25180-f669-11ea-8bf5-ddd82289029a.png)

**Comment by SoloCarryGuy** [comment]
Okay. Will do that. Thanks. You just saved a lot of my time.

**Comment by SoloCarryGuy** [comment]
@ulvido Hello, I needed a bit of help again. This time with the save games method. 

1 - My game has three type of data it needs to save, data regarding levels, regarding boosters that player has and amount of gold player has earned, I have a dictionaries for every one of them. Should I make a single dictionary out of all three or should I upload three dictionaries.

2 - If I should make a single dictionary how do I do that and if I should upload them separately how do I check that all of them are uploaded because there is only one call back _on_save_game_success

**Comment by ulvido** [comment]
sorry. I didn't ever use the plugins save method to the play games. I only used local save method in godot.

**Comment by SoloCarryGuy** [comment]
Oh, okay.
