### ISSUE TITLE
leaderboards don't work

### ISSUE THREAD

**Issue by maxyboiii** [cgisca/PGSGP#4]
i have a simple script with a button, and leaderboard doesn't work...

var score = 10
var play_games_services

func _ready():
	if Engine.has_singleton("PlayGameServices"):
		play_games_services = Engine.get_singleton("PlayGameServices")
	play_games_services.init(get_instance_id(), true)
	play_games_services.sign_in()

func _on_leaderboardbutton_pressed():
	play_games_services.submit_leaderboard_score("*my_leaderboard_id*", score)
	play_games_services.show_leaderboard("*my_leaderboard_id*")

**Comment by MikaelMollberg** [comment]
I had this issue as well for a while, but it was a configuration problem and had nothing to do with the plugin. It's working well for me now. 

Make sure that the credentials and the SHA1 of the keystore matches what you have in Google Play.

**Comment by maxyboiii** [comment]
> 
> 
> I had this issue as well for a while, but it was a configuration problem and had nothing to do with the plugin. It's working well for me now.
> 
> Make sure that the credentials and the SHA1 of the keystore matches what you have in Google Play.

do you know how to fix this SHA1? also thanks btw

**Comment by MikaelMollberg** [comment]
You can take a look at https://developers.google.com/games/services/android/troubleshooting#check_the_certificate_fingerprint

I assume that you have uploaded a keystore file to the google play console. You can verify this on the "App signing" page. The SHA1 must be the same there, in your local keystore file and here in the oauth https://console.cloud.google.com/apis/credentials.

Note that if you start the game from Godot the debug keystore is used by default which may be different from the keystore you have uploaded.

**Comment by cgisca** [comment]
@maxyboiii  I am closing this issue as it seems to be the problem with SHA1.
