### ISSUE TITLE
Stuck forever after tapping on account to sign in if using initWithSavedGames instead of just init

### ISSUE THREAD

**Issue by oneseedfruit** [cgisca/PGSGP#57]
![20210201_193002](https://user-images.githubusercontent.com/5054104/106453483-5bb6b400-64c4-11eb-9823-fa9e9e0f3c1f.jpg)
Godot 3.2.3
Android 10

After tapping on an account to sign in if using `initWithSavedGames` instead of just `init`, the next popup appears and just keeps loading forever.

"Saved Games" is enabled in the Google Play Console and these are all added:

- Google Play Game Services
- Google Play Game Management
- Google Drive API

if `init` is used instead, it signs in almost perfectly except the `account_id` is always null in `_on_sign_in_success`.

**Comment by oneseedfruit** [comment]
Probably caused by: https://github.com/cgisca/PGSGP/issues/58

**Comment by tpaulino7** [comment]
Hi,
I'm having this exact same issue when moving to initWithSavedGames.
Saw that you made a PR with a fix and would like to check if it solves this issue for me as well.
Do you the release files somewhere I could use?
Thanks

**Comment by oneseedfruit** [comment]
@tpaulino7 

Hi, I've just uploaded it [here](https://github.com/oneseedfruit/PGSGP/releases/tag/3.0.0) for you. Hope it helps.

**Comment by tpaulino7** [comment]
Hi,
Thanks! I've tested but unfortunately the behavior seems the same,  works fine for the init, stays in that loading white screen for the initWithSavedGames. It should be something else missing in my case.
Also, I had to pass the extra arguments (request_email, request_profile, request_token) to the function init, gives an error otherwise. 
Thanks anyway for making the files available!

**Comment by oneseedfruit** [comment]
You could try:

1. In your Google Play Console, go to Play Games Services -> Configuration, click "Edit properties" and make sure "Saved games" is enabled, then publish the changes. If it's enabled for the first time you might have to wait up to 24 hours.
2. Also in Play Games Services -> Configuration, see under "Credentials". Make sure your credentials (OAuth clients) are set up correctly.
